{
 "title": "NVIDIA GPU Edited",
 "description": "Dashboard for the nvidia-smi-exporter. Some panels may not contain data for unsupported nvidia-smi query fields.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "nvidia_metrics",
    "query": "{__name__=~\"^nvidia_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "repeat": "nvidia_metrics",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "title": "$nvidia_metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "$nvidia_metrics" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "content": "## nvidia-smi-exporter\nSome panels within this dashboard may not be populated if the GPU being scraped do not support those metrics.\n\nSee [Dashboard section](https://github.com/glynternet/nvidia-smi-exporter#dashboard) of the repo README for how to remove unsupported metric panels."
  },
  {
   "title": "nvidia_clocks_applications_gr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_applications_gr" }
   ]
  },
  {
   "title": "nvidia_clocks_applications_graphics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_applications_graphics"
    }
   ]
  },
  {
   "title": "nvidia_clocks_applications_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_applications_mem" }
   ]
  },
  {
   "title": "nvidia_clocks_applications_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_applications_memory"
    }
   ]
  },
  {
   "title": "nvidia_clocks_current_graphics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_current_graphics" }
   ]
  },
  {
   "title": "nvidia_clocks_current_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_current_memory" }
   ]
  },
  {
   "title": "nvidia_clocks_current_sm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_current_sm" }
   ]
  },
  {
   "title": "nvidia_clocks_current_video",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_current_video" }
   ]
  },
  {
   "title": "nvidia_clocks_default_applications_gr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_default_applications_gr"
    }
   ]
  },
  {
   "title": "nvidia_clocks_default_applications_graphics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_default_applications_graphics"
    }
   ]
  },
  {
   "title": "nvidia_clocks_default_applications_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_default_applications_mem"
    }
   ]
  },
  {
   "title": "nvidia_clocks_default_applications_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_default_applications_memory"
    }
   ]
  },
  {
   "title": "nvidia_clocks_gr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_gr" }
   ]
  },
  {
   "title": "nvidia_clocks_max_gr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_max_gr" }
   ]
  },
  {
   "title": "nvidia_clocks_max_graphics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_max_graphics" }
   ]
  },
  {
   "title": "nvidia_clocks_max_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_max_mem" }
   ]
  },
  {
   "title": "nvidia_clocks_max_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_max_memory" }
   ]
  },
  {
   "title": "nvidia_clocks_max_sm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_max_sm" }
   ]
  },
  {
   "title": "nvidia_clocks_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_mem" }
   ]
  },
  {
   "title": "nvidia_clocks_sm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_sm" }
   ]
  },
  {
   "title": "nvidia_clocks_throttle_reasons_gpu_idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_throttle_reasons_gpu_idle"
    }
   ]
  },
  {
   "title": "nvidia_clocks_throttle_reasons_hw_power_brake_slowdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_throttle_reasons_hw_power_brake_slowdown"
    }
   ]
  },
  {
   "title": "nvidia_clocks_throttle_reasons_hw_slowdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_throttle_reasons_hw_slowdown"
    }
   ]
  },
  {
   "title": "nvidia_clocks_throttle_reasons_hw_thermal_slowdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_throttle_reasons_hw_thermal_slowdown"
    }
   ]
  },
  {
   "title": "nvidia_clocks_throttle_reasons_sw_thermal_slowdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_throttle_reasons_sw_thermal_slowdown"
    }
   ]
  },
  {
   "title": "nvidia_clocks_throttle_reasons_sync_boost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_clocks_throttle_reasons_sync_boost"
    }
   ]
  },
  {
   "title": "nvidia_clocks_video",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_clocks_video" }
   ]
  },
  {
   "title": "nvidia_driver_version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_driver_version" }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_aggregate_device_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_aggregate_device_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_aggregate_l1_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_aggregate_l1_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_aggregate_l2_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_aggregate_l2_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_aggregate_register_file",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_aggregate_register_file"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_aggregate_texture_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_aggregate_texture_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_aggregate_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_aggregate_total"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_volatile_l1_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_volatile_l1_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_volatile_l2_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_volatile_l2_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_volatile_register_file",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_volatile_register_file"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_volatile_texture_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_volatile_texture_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_corrected_volatile_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_corrected_volatile_total"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_aggregate_device_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_aggregate_device_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_aggregate_l1_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_aggregate_l1_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_aggregate_l2_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_aggregate_l2_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_aggregate_register_file",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_aggregate_register_file"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_aggregate_texture_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_aggregate_texture_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_aggregate_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_aggregate_total"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_volatile_device_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_volatile_device_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_volatile_l1_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_volatile_l1_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_volatile_l2_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_volatile_l2_cache"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_volatile_register_file",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_volatile_register_file"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_volatile_texture_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_volatile_texture_memory"
    }
   ]
  },
  {
   "title": "nvidia_ecc_errors_uncorrected_volatile_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_ecc_errors_uncorrected_volatile_total"
    }
   ]
  },
  {
   "title": "nvidia_encoder_stats_averageFps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_encoder_stats_averageFps"
    }
   ]
  },
  {
   "title": "nvidia_encoder_stats_averageLatency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_encoder_stats_averageLatency"
    }
   ]
  },
  {
   "title": "nvidia_encoder_stats_sessionCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_encoder_stats_sessionCount"
    }
   ]
  },
  {
   "title": "nvidia_enforced_power_limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_enforced_power_limit" }
   ]
  },
  {
   "title": "nvidia_fan_speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_fan_speed" }
   ]
  },
  {
   "title": "nvidia_memory_free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_memory_free" }
   ]
  },
  {
   "title": "nvidia_memory_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_memory_total" }
   ]
  },
  {
   "title": "nvidia_memory_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_memory_used" }
   ]
  },
  {
   "title": "nvidia_power_default_limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_power_default_limit" }
   ]
  },
  {
   "title": "nvidia_power_draw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_power_draw" }
   ]
  },
  {
   "title": "nvidia_power_limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_power_limit" }
   ]
  },
  {
   "title": "nvidia_power_management",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_power_management" }
   ]
  },
  {
   "title": "nvidia_power_max_limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_power_max_limit" }
   ]
  },
  {
   "title": "nvidia_power_min_limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_power_min_limit" }
   ]
  },
  {
   "title": "nvidia_pstate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_pstate" }
   ]
  },
  {
   "title": "nvidia_pstate_unparseable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_pstate_unparseable" }
   ]
  },
  {
   "title": "nvidia_query_field_unsupported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_query_field_unsupported" }
   ]
  },
  {
   "title": "nvidia_retired_pages_dbe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_retired_pages_dbe" }
   ]
  },
  {
   "title": "nvidia_retired_pages_double_bit_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_retired_pages_double_bit_count"
    }
   ]
  },
  {
   "title": "nvidia_retired_pages_pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_retired_pages_pending" }
   ]
  },
  {
   "title": "nvidia_retired_pages_sbe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_retired_pages_sbe" }
   ]
  },
  {
   "title": "nvidia_retired_pages_single_bit_ecc_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_retired_pages_single_bit_ecc_count"
    }
   ]
  },
  {
   "title": "nvidia_temperature_gpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_temperature_gpu" }
   ]
  },
  {
   "title": "nvidia_unknown_error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_unknown_error" }
   ]
  },
  {
   "title": "nvidia_unparseable_query_result_value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_unparseable_query_result_value"
    }
   ]
  },
  {
   "title": "nvidia_utilization_gpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_utilization_gpu" }
   ]
  },
  {
   "title": "nvidia_utilization_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_utilization_memory" }
   ]
  }
 ]
}